# Aggregated ClusterRole for Kyverno RBAC generation capabilities
# This gets automatically aggregated into kyverno:background-controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:rbac-generatecontroller
  labels:
    # Aggregation label to include in background-controller role
    rbac.kyverno.io/aggregate-to-background-controller: "true"
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/part-of: kyverno
  annotations:
    policies.kyverno.io/description: "RBAC permissions for Kyverno to generate and manage RBAC resources"
rules:
# RBAC management permissions - all verbs for complete control
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["*"]
# Namespace and Group read access for policy logic
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["user.openshift.io"]
  resources: ["groups"]
  verbs: ["get", "list", "watch"]
