# Validation Policy - Enforce naming standards (NS + Group)
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-rbac-ns-standards
  annotations:
    policies.kyverno.io/title: "Enforce RBAC NS Pattern Standards"
    policies.kyverno.io/category: "Multi-Tenancy"
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: "Namespace, Group"
    kyverno.io/kyverno-version: "1.15.1"
    policies.kyverno.io/minversion: "1.15.0"
    kyverno.io/kubernetes-version: "1.24-1.29"
    policies.kyverno.io/description: >-
      Enforces standardized RBAC group name patterns. Normalizes comma+space
      separated lists from labels and validates group names for namespaces and
      OpenShift Group objects. Uses a 3-state precondition to control inclusion.
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: rbac-validation
    app.kubernetes.io/part-of: ldap-integration
spec:
  validationFailureAction: Audit
  background: true
  rules:

  # Validate namespace label group values against allowed pattern
  - name: validate-namespace-groups
    match:
      any:
      - resources:
          kinds: ["Namespace"]
    preconditions:
      any:
      # Skip system namespaces unless explicitly opted in
      - key: "{{ request.object.metadata.name }}"
        operator: AnyNotIn
        value: ["kube-system", "kube-public", "kube-node-lease", "default", "kyverno"]
      # Allow if exclude-rbac is explicitly false
      - key: "{{ request.object.metadata.labels.\"kyverno.io/exclude-rbac\" || '' }}"
        operator: Equals
        value: "false"
    context:
      - name: all_groups
        variable:
          jmesPath: >
            split(
              regex_replace_all(
                to_string(join(',', [
                  request.object.metadata.labels."oim-ns-admin" || '',
                  request.object.metadata.labels."oim-ns-edit"  || '',
                  request.object.metadata.labels."oim-ns-view"  || ''
                ])),
                '\\s*[,]+\\s*', ','
              ),
              ','
            ) | [?@ != '']
    validate:
      message: "RBAC Standards Violation: All group names must follow app-ocp-rbac-{team}-ns-(admin|developer|audit) pattern."
      foreach:
        - list: "all_groups"
          deny:
            conditions:
              any:
              - key: "{{ element }}"
                operator: NotEqual
                value: ""

  # Validate OpenShift Group objects against allowed pattern
  - name: validate-openshift-groups
    match:
      any:
      - resources:
          kinds: ["user.openshift.io/v1/Group"]
          names: ["app-ocp-rbac-*"]
    # Preconditions removed - using names filter in match instead
    validate:
      message: "RBAC Standards Violation: Group '{{ request.object.metadata.name }}' must follow app-ocp-rbac-{team}-(ns|cluster)-(admin|developer|audit)."
      deny:
        conditions:
          any:
          - key: "{{ request.object.metadata.name }}"
            operator: NotEqual
            value: ""

  # Recommend RBAC labels are present on namespaces
  - name: require-rbac-labels
    match:
      any:
      - resources:
          kinds: ["Namespace"]
    preconditions:
      any:
      # Skip system namespaces unless explicitly opted in
      - key: "{{ request.object.metadata.name }}"
        operator: AnyNotIn
        value: ["kube-system", "kube-public", "kube-node-lease", "default", "kyverno"]
      # Allow if exclude-rbac is explicitly false  
      - key: "{{ request.object.metadata.labels.\"kyverno.io/exclude-rbac\" || '' }}"
        operator: Equals
        value: "false"
    validate:
      message: "RBAC Policy Recommendation: add at least one label (oim-ns-admin|oim-ns-edit|oim-ns-view) to enable team access."
      deny:
        conditions:
          all:
          - key: "{{ request.object.metadata.labels.\"oim-ns-admin\" || '' }}"
            operator: Equals
            value: ""
          - key: "{{ request.object.metadata.labels.\"oim-ns-edit\" || '' }}"
            operator: Equals
            value: ""
          - key: "{{ request.object.metadata.labels.\"oim-ns-view\" || '' }}"
            operator: Equals
            value: ""
