# Generate Policy - Namespace RoleBindings (short names, correct foreach)
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-namespace-rolebindings
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: "Generate Namespace RoleBindings"
    policies.kyverno.io/category: "Multi-Tenancy"
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: "RoleBinding"
    kyverno.io/kyverno-version: "1.15.1"
    policies.kyverno.io/minversion: "1.15.0"
    kyverno.io/kubernetes-version: "1.24-1.29"
    policies.kyverno.io/description: >-
      Generates per-group RoleBindings in each namespace from labels:
      oim-ns-admin, oim-ns-edit, oim-ns-view. Names are short and role-aligned.
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: rbac-generation
    app.kubernetes.io/part-of: ldap-integration
spec:
  generateExisting: true
  background: true
  rules:

  # ns-admin → ClusterRole admin
  - name: generate-ns-admin-rolebindings
    match:
      any:
      - resources:
          kinds: ["Namespace"]
    preconditions:
      all:
      # Skip system namespaces unless explicitly opted in
      - key: "{{ request.object.metadata.name }}"
        operator: AnyNotIn
        value: ["kube-system", "kube-public", "kube-node-lease", "default"]
      # Only process if admin groups are present
      - key: "{{ request.object.metadata.labels.\"oim-ns-admin\" || '' }}"
        operator: NotEquals
        value: ""
      # Don't process if explicitly excluded
      - key: "{{ request.object.metadata.labels.\"kyverno.io/exclude-rbac\" || '' }}"
        operator: NotEquals
        value: "true"
    context:
      - name: admin_groups
        variable:
          jmesPath: split(request.object.metadata.labels."oim-ns-admin" || '', ',') | [?@ != '' && @ != 'null']
      - name: namespace_name
        variable:
          jmesPath: request.object.metadata.name
    generate:
      synchronize: true
      foreach:
      - list: "admin_groups"
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: "{{ element }}-admin-rb"
        namespace: "{{ request.object.metadata.name }}"
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
              rbac.ocp.io/role-type: ns-admin
              rbac.ocp.io/group-name: "{{ element }}"
            annotations:
              kyverno.io/policy: generate-namespace-rolebindings
              kyverno.io/rule: generate-ns-admin-rolebindings
              kyverno.io/source-label: oim-ns-admin
          subjects:
          - kind: Group
            name: "{{ element }}"
            apiGroup: rbac.authorization.k8s.io
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: admin

  # ns-developer → ClusterRole edit
  - name: generate-ns-developer-rolebindings
    match:
      any:
      - resources:
          kinds: ["Namespace"]
    preconditions:
      all:
      # Skip system namespaces unless explicitly opted in
      - key: "{{ request.object.metadata.name }}"
        operator: AnyNotIn
        value: ["kube-system", "kube-public", "kube-node-lease", "default"]
      # Only process if edit groups are present
      - key: "{{ request.object.metadata.labels.\"oim-ns-edit\" || '' }}"
        operator: NotEquals
        value: ""
      # Don't process if explicitly excluded
      - key: "{{ request.object.metadata.labels.\"kyverno.io/exclude-rbac\" || '' }}"
        operator: NotEquals
        value: "true"
    context:
      - name: edit_groups
        variable:
          jmesPath: split(request.object.metadata.labels."oim-ns-edit" || '', ',') | [?@ != '' && @ != 'null']
      - name: namespace_name
        variable:
          jmesPath: request.object.metadata.name
    generate:
      synchronize: true
      foreach:
      - list: "edit_groups"
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: "{{ element }}-edit-rb"
        namespace: "{{ request.object.metadata.name }}"
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
              rbac.ocp.io/role-type: ns-developer
              rbac.ocp.io/group-name: "{{ element }}"
            annotations:
              kyverno.io/policy: generate-namespace-rolebindings
              kyverno.io/rule: generate-ns-developer-rolebindings
              kyverno.io/source-label: oim-ns-edit
          subjects:
          - kind: Group
            name: "{{ element }}"
            apiGroup: rbac.authorization.k8s.io
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: edit

  # ns-audit → ClusterRole view
  - name: generate-ns-audit-rolebindings
    match:
      any:
      - resources:
          kinds: ["Namespace"]
    preconditions:
      all:
      # Skip system namespaces unless explicitly opted in
      - key: "{{ request.object.metadata.name }}"
        operator: AnyNotIn
        value: ["kube-system", "kube-public", "kube-node-lease", "default"]
      # Only process if view groups are present
      - key: "{{ request.object.metadata.labels.\"oim-ns-view\" || '' }}"
        operator: NotEquals
        value: ""
      # Don't process if explicitly excluded
      - key: "{{ request.object.metadata.labels.\"kyverno.io/exclude-rbac\" || '' }}"
        operator: NotEquals
        value: "true"
    context:
      - name: view_groups
        variable:
          jmesPath: split(request.object.metadata.labels."oim-ns-view" || '', ',') | [?@ != '' && @ != 'null']
      - name: namespace_name
        variable:
          jmesPath: request.object.metadata.name
    generate:
      synchronize: true
      foreach:
      - list: "view_groups"
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        name: "{{ element }}-view-rb"
        namespace: "{{ request.object.metadata.name }}"
        data:
          metadata:
            labels:
              app.kubernetes.io/managed-by: kyverno
              rbac.ocp.io/role-type: ns-audit
              rbac.ocp.io/group-name: "{{ element }}"
            annotations:
              kyverno.io/policy: generate-namespace-rolebindings
              kyverno.io/rule: generate-ns-audit-rolebindings
              kyverno.io/source-label: oim-ns-view
          subjects:
          - kind: Group
            name: "{{ element }}"
            apiGroup: rbac.authorization.k8s.io
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: view
